import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/FB_IMG_1701639746682.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "" : "dark"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Maher ZARAI
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              QA Automation Engineer | Vermeg
            </h3>

            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://www.linkedin.com/in/maher-zarai-a5098a86/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillLinkedin />
              </a>
            </div>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div >
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Passionate about software testing and validation, ISTQB and A4Q
              certified. I am determined to improve my skills to work on
              projects that will impact our future. Strongly motivated for new
              challenges and opportunities.
            </p>
          </div>
          <div className="flex-container">
            <div className="work-experience">
              <h3 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Work Experience:</h3>
              <div className="content">
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                <h2 className="colored-header">January 2023 - Present: QA Automation Engineer</h2>
                <p>
                  <em className="text-2xl py-2">Company:</em> Vermeg For Banking And Insurance Software
                </p>
                <p>
                  <em className="text-2xl py-2">Description:</em>Cypress, Javascript, Cucumber, BDD, VS,
                  Java, UML, Eclipse, ReadyApi, Postman SwagirUi, Linux, sql
                  developer, API implimentation, API testing, CI/CD...{" "}
                </p>

                <h2 className="colored-header">Sept 2021 - Jan 2023: QA Software Analyst Engineer</h2>
                <p>
                  <em className="text-2xl py-2">Company:</em> New Access
                </p>
                <p>
                  <em className="text-2xl py-2">Description:</em>QA and UNIX Tests Environment at New Access
                  Center Tunis in Banking Segment: APSYS Core Banking: A banking
                  solution front-to-back office for private banking and asset
                  management intended for clients primarily in Geneva, Zurich,
                  Luxembourg, Panama, Bahamas ... My tasks are as follows:
                  <p>- Design, writing and Execution of test cases</p>
                  <p>- Analysis and writing of test specifications</p>
                  <p>- Execution of unit tests, regression tests and functional tests on various projects related to Financial market</p>
                  <p>- Writing Test incident reports and Execution of confirmation tests</p>
                  <p>- Execution of Test systems when receiving a new product version</p>
                  <p>- Administration and automation of tasks on servers Tests:</p>
                  <p>- Management and preparation of test environments for the QA team (OS IBM AIX and Red Hat)</p>
                  <p>- Provide application support for the QA team in case when there are problems in the environments</p>
                  <p>- Planning and monitoring of automated tasks: Backup a database, file cleaning, Disk space control, start / stop environments</p>
                  <p>- Installation of new product versions (client and server), received and make the migration of Oracle databases (12C to 19C)</p>
                  <p>- Development and maintenance of automatic test case with Selenium tool</p>
                  <p>- Maintenance of central functions based in UNIX that will be used to develop tools SHELL</p>
                  <p>- Preparation of environments for end of day operations and execution of the procedure in a real context for a bank</p>
                </p>

                <h2 className="colored-header">July 2019 - August 2021: Stress Engineer</h2>
                <p>
                  <em className="text-2xl py-2">Company:</em> Sogeclair Aerospace
                </p>
                <p>
                  <em className="text-2xl py-2">Description:</em>
                <p>- Static analysis of derogations. </p>
                <p>- Check of non-conformity repair solutions made by the T100 design team.</p>
                <p>- Analysis of static calculation, fatigue and damage tolerance of a non-conformity derogations. </p>
                <p>- Self-check of work done based on a checklist. </p>
                <p>- Justifications of repair solutions and response to waivers in T300 on the SAP Tool. </p>
                <p>- Creation and data entry of numerical models in finite elements FE and BEM.</p>
                </p>

                <h2 className="colored-header">Dec 2016 - June 2019: Test Product Engineer</h2>
                <p>
                  <em className="text-2xl py-2">Company:</em> Lotte Advanced Materials
                </p>
                <p>
                  <em className="text-2xl py-2">Description:</em>
                <p>- Pilot and manage project material validation and approval tests from the validation plan and customer specifications (Renault, AUDI, VOLKSWAGEN, PSA, VOLVO...). </p>
                <p>- Manage and pilot the reinforced product audit activity for new projects (protocol, sampling, tests...). </p>
                <p>- Perform reliability and life cycle tests for major automotive customers. </p>
                <p>- Perform mechanical, climatic, vibration tests and R&D performance tests. </p>
                <p>- Preparation of test methods.</p>
                </p>
              </p>
              </div>
            </div>
          <div className="education">
          <h3 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Education:</h3>
          <div className="content">
                        
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <h2 className="colored-header">
                September 2022 - June 2024: Master degree in Software
                Engineering
              </h2>
              <p>
                <em className="text-2xl py-2">Speciality:</em> Software Engineering
              </p>
              <p>
                <em className="text-2xl py-2">Institution:</em> Higher Institute of Computer Science of
                Tunis
              </p>

              <h2 className="colored-header">
                September 2014 - September 2015: Master Degree in Composite
                Materials
              </h2>
              <p>
                <em className="text-2xl py-2">Speciality:</em> Materials Engineering
              </p>
              <p>
                <em className="text-2xl py-2">Institution:</em> Le Havre Univeristy
              </p>

              <h2 className="colored-header">
                September 2010 - June 2013 : Engineering Degree in Materials
                sciences
              </h2>
              <p>
                <em className="text-2xl py-2">Speciality:</em> Materials Engineering
              </p>
              <p>
                <em className="text-2xl py-2">Institution:</em> National Engineering School Of Sfax
              </p>

              <h2 className="colored-header">September 2008 - June 2010 : Preparotry Class </h2>
              <p>
                <em className="text-2xl py-2">Speciality:</em> Mathematics and Physics (MP)
              </p>
              <p>
                <em className="text-2xl py-2">Institution:</em> Preparatory Institute for Engineering
                Studies of Sfax
              </p>

              <h2>September 2007 - June 2008: Baccalaureate Degree</h2>
              <p>
                <em className="text-2xl py-2">Specialty:</em> Baccalaureate Degree in Mathematics
              </p>
          </p>
          </div>
          </div>

          <style jsx>{`
      .flex-container {
        display: flex;
        flex-wrap: wrap;
        gap: 20px; /* Adjust the gap as needed */
      }

      .work-experience,
      .education {
        width: 48%; /* Adjust the width as needed */
      }

      .content {
        margin-top: 10px; /* Adjust the margin as needed */
      }

      .colored-header {
        color: #D2B48C; /* Set your desired color */
      }

      .flex-container > * {
        box-sizing: border-box;
      }
    `}</style>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">Skills:</h3>
              <p className="py-2">Software Testing</p>
              <h4 className="py-4 text-teal-600">Test Automation</h4>
              <p className="text-gray-800 py-1">Writing test cases</p>
              <p className="text-gray-800 py-1">Selenium and Cypress</p>
              <p className="text-gray-800 py-1">
                API implimentation and testing
              </p>
              <p className="text-gray-800 py-1">Cucumber, BDD, CI/CD</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Skills :</h3>
              <p className="py-2">Coding skills</p>
              <h4 className="py-4 text-teal-600">Coding Tools I Use</h4>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">NodeJs</p>
              <p className="text-gray-800 py-1">C/C++</p>
              <p className="text-gray-800 py-1">Python</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">skills</h3>
              <p className="py-2">Certifications</p>
              <h4 className="py-4 text-teal-600">
                IBM: Linux and Private Cloud Administration
              </h4>
              <p className="text-gray-800 py-1">GASQ: A4Q Selenium Java </p>
              <p className="text-gray-800 py-1">
                GASQ: ISTQB: Certified Tester Foundation Level
              </p>
              <p className="text-gray-800 py-1">Scrum Fundemental Certified</p>
            </div>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <Image src={consulting} width={100} height={100} />
            <h3 className="text-lg font-medium pt-8 pb-2 ">skills</h3>
            <p className="py-2"></p>
            <h2 className="py-4 text-teal-600">Languages:</h2>

            <p className="text-gray-800 py-1">Arabic: Native</p>
            <p className="text-gray-800 py-1">French: Fluent</p>
            <p className="text-gray-800 py-1">English: Intermediate</p>
          </div>
        </section>
      </main>
    </div>
  );
}
