import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Maher ZARAI CV </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Maher ZARAI
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Data Quality | Student 
            </h3>
         
           <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                 <a href="https://www.linkedin.com/in/maher-zarai/" target="_blank" rel="noopener noreferrer">
                   <AiFillLinkedin />
                 </a>
            </div>

           
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
          <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
          Passionate about software testing and validation, ISTQB and A4Q certified. 
          I am determined to improve my skills to work on projects that will impact our future. 
          Strongly motivated for new challenges and opportunities.
            </p>
            <h3 className="text-3xl py-1 dark:text-white ">Work Experience:</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            <h2>January 2023 - Present: QA Automation Engineer</h2>
  <p><em>Company:</em> Vermeg For Banking And Insurance Software</p>
  <p><em>Description:</em>Cypress, Javascript, Cucumber, BDD, VS, Java, UML, Eclipse, ReadyApi, Postman
  SwagirUi, Linux, sql developer, API implimentation, API testing, CI/CD... </p>

  <h2>Sept 2021 - Jan 2023: QA Software Analyst Engineer</h2>
  <p><em>Company:</em> New Access</p>
  <p><em>Description:</em>QA and UNIX Tests Environment at New Access Center Tunis in Banking Segment: 
  APSYS Core Banking: A banking solution front-to-back office for private banking 
  and asset management intended for clients primarily in Geneva, Zurich, Luxembourg, Panama, Bahamas ... 
    My tasks are as follows:
    o Design, writing and Execution of test cases
    o Analysis and writing of test specifications
    o Execution of unit tests, regression tests and functional tests on various projects related to Financial market
    o Writiing Test incident reports and Execution of confirmation tests
    o Execution of Test systems when receiving a new product version
    - Administration and automation of tasks on servers Tests:
    o Management and preparation of test environments for the QA team (OS IBM AIX and Red Hat)
    o Provide application support for the QA team in case when there are problems in the environments
    o Planning and monitoring of automated tasks: Backup a database, file cleaning, Disk space control, start / stop environments
    o Installation of new product versions (client and server), received and make the migration of Oracle databases (12C to 19C)
    o Development and maintenance of automatic test case with Selenium tool
    o Maintenance of central functions based in UNIX that will be used to develop tools SHELL
    o Preparation of environments for end of day operations and execution of the procedure in a real context for a bank
    </p>

  <h2>July 2019 - August 2021: Stress Engineer</h2>
  <p><em>Company:</em> Sogeclair Aerospace</p>
  <p><em>Description:</em>o Static analysis of derogations.
  o Check of non-conformity repair solutions made by the T100 design team.
  o Analysis of static calculation, fatigue and damage tolerance of a non-conformity derogations.
  o Self-check of work done based on a checklist.
  o Justifications of repair solutions and response to waivers in T300 on the SAP Tool.
  o Creation and data entry of numerical models in finite elements FE and BEM.
 </p>
 
 
  <h2>Dec 2016 - June 2019: Test Product Engineer</h2>
  <p><em>Company:</em> Lotte Advanced Materials</p>
  <p><em>Description:</em>oPilot and manage project material validation and approval tests 
  from the validation plan and customer specifications (Renault, AUDI, VOLKSWAGEN, PSA, VOLVO...).
  o Manage and pilot the reinforced product audit activity for new projects (protocol, sampling, tests...).
  o Perform reliability and life cycle tests for major automotive customers.
  o Perform mechanical, climatic, vibration tests and R&D performance tests.
  o Preparation of test methods.
 </p>
            </p>
              <h3 className="text-3xl py-1 dark:text-white ">Education:</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            <h2>September 20222 - June 2024: Master degree in Software Engineering</h2>
            <p><em>Speciality:</em> Software Engineering</p>
  <p><em>Institution:</em> Higher Institute of Computer Science of Tunis</p>

  <h2>September 2014 - September 2015: Master Degree in Composite Materials</h2>
  <p><em>Speciality:</em> Materials Engineering</p>
  <p><em>Institution:</em> Le Havre Univeristy</p>

  <h2>September 2010 - June 2013 : Engineering Degree in Materials sciences</h2>
  <p><em>Speciality:</em> Materials Engineering</p>
  <p><em>Institution:</em> National Engineering School Of Sfax</p>

  <h2>September 2008 - June 2010 :  Preparotry Class </h2>
  <p><em>Speciality:</em> Mathematics and Physics (MP)</p>
  <p><em>Institution:</em>  Preparatory Institute for Engineering Studies of Sfax</p>

  <h2>September 2007 - June 2008: Baccalaureate Degree</h2>
  <p><em>Specialty:</em> Baccalaureate Degree in Mathematics</p>
            </p>
          </div>
          

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
              Skills:
              </h3>
              <p className="py-2">
              Software Testing
              </p>
              <h4 className="py-4 text-teal-600">Test Automation</h4>
              <p className="text-gray-800 py-1">Writing test cases</p>
              <p className="text-gray-800 py-1">Selenium and Cypress</p>
              <p className="text-gray-800 py-1">API implimentation and testing</p>
              <p className="text-gray-800 py-1">Cucumber, BDD, CI/CD</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                 Skills :
              </h3>
              <p className="py-2">
                Coding skills
              </p>
              <h4 className="py-4 text-teal-600">Coding Tools I Use</h4>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">NodeJs</p>
              <p className="text-gray-800 py-1">C/C++</p>
              <p className="text-gray-800 py-1">Python</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">skills</h3>
              <p className="py-2">
              Certifications
              </p>
              <h4 className="py-4 text-teal-600">IBM: Linux and Private Cloud Administration</h4>
              <p className="text-gray-800 py-1">GASQ: A4Q Selenium Java </p>
              <p className="text-gray-800 py-1">GASQ: ISTQB: Certified Tester Foundation Level</p>
              <p className="text-gray-800 py-1">Scrum Fundemental Certified</p>
            </div>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">skills</h3>
              <p className="py-2">
              
              </p>
              <h2 className="py-4 text-teal-600">Languages:</h2>
            
              <p className="text-gray-800 py-1">Arabic: Native</p>
              <p className="text-gray-800 py-1">French: Fluent</p>
              <p className="text-gray-800 py-1">English: Intermediate</p>
            </div>
        </section>
      </main>
    </div>
  );
}